eza-community/eza

completions/fish/exa.fish

https://github.com/ogham/exa/pull/1219

(exa PR) 1219: fix fish completion for -i/--inode option

---

src/options/error.rs

https://github.com/ogham/exa/pull/1099

(exa PR) 1099: fix some typos

---

completions/fish/eza.fish
completions/zsh/_eza

This adds status completions for https://github.com/cafkafk/eza/pull/62
This doesn't add completions for bash https://github.com/cafkafk/eza/issues/76

feat(git): add git-status-.* completions

---

.gitignore
flake.lock
flake.nix
rust-toolchain.toml
treefmt.nix

see: https://github.com/cafkafk/eza/issues/72

ci: add trivial nix flake

---

README.md
devtools/dev-create-test-filesystem.sh
devtools/dev-fixtures.sh
devtools/dev-run-debug.sh
devtools/dev-run-release.sh
devtools/dev-set-up-environment.sh
xtests/run.sh

see: https://github.com/cafkafk/eza/issues/72

doc(nix): document nix flake

---

src/output/icons.rs

github.com/ogham/exa/pulls/1085

(exa PR) 1085

---

src/output/icons.rs

github.com/ogham/exa/pulls/1057

(exa PR) 1057: add icon for Vagrantfile

---

src/output/icons.rs

https://github.com/ogham/exa/pull/1006

(exa PR) 1006: Add git icon to .gitignore_global file

---

src/info/filetype.rs
src/output/icons.rs

github.com/ogham/exa/pulls/1094

(exa PR) 1094

---

src/output/icons.rs

github.com/ogham/exa/pulls/1120

(exa PR) 1120

---

src/output/icons.rs

github.com/ogham/exa/pulls/1128

(exa PR) 1128

---

src/output/icons.rs

github.com/ogham/exa/pulls/1162

(exa PR) 1162

---

src/output/icons.rs

https://github.com/ogham/exa/pull/1194

(exa PR) 1194: add Emacs icon for .el and org-mode for .org

---

src/info/sources.rs

https://github.com/ogham/exa/pull/1121

(exa PR) 1121: Add some compiled file

---

build.rs

Tracking issue: https://github.com/cafkafk/eza/issues/97

fix: update --version info

---

src/output/file_name.rs
src/output/grid.rs

Tracking-issue: https://github.com/cafkafk/eza/issues/103

fix: output wraps in terminal

---

CHANGELOG.md
Cargo.lock
Cargo.toml

chore: release 0.10.5

---

.github/workflows/unit-tests.yml

This adds clippy lints to CI testing.
See #119. This helps automate code quality checks.
Testing will happen in this PR, where we see whether the clippy tests run via github actions.

Add Clippy To CI Tests

---

.github/labeler.yml
.github/workflows/flake.yml
flake.nix

This adds a github actions check for flakes, based on https://github.com/lilyinstarlight/foosteros.
This adds `.github/workflows/flake.yml` from https://github.com/lilyinstarlight/foosteros, with the cachix parts removed.
This will be helpful as we ramp up our flake efforts. 
It hasn't! I'm testing this via the github actions run on push.
Not appropriate.

ci: nix flake check

---

README.md

Now we have a Gitter room :rocket:
Added badge to README

docs: add badge for eza gitter/matrix room

---

rust-toolchain.toml

build: use rust stable

---

flake.nix

This makes it easier for me to and other devs (and powerusers) to test and run
the most bleeding edge of eza.

build(nix): add unstable package

---

README.md

docs(readme): add homebrew, misc fixes

---

tests/references/eza-blocksize.txt
tests/references/eza-long.txt
tests/references/main.txt
tests/tapes/eza-blocksize.tape
tests/tapes/eza-long.tape
tests/tapes/main.tape

test(itest): stabilize testing without sandbox

---

flake.nix
tests/tapes/eza-blocksize.tape
tests/tapes/eza-long.tape
tests/tapes/main.tape

- test(itest): stabilize testing without sandbox
- test(itest): disable gif rendering

disable gif rendering in itests

---

README.md

Add star history to README.md :heart:
[![Star History Chart](https://api.star-history.com/svg?repos=eza-community/eza&type=Date)](https://star-history.com/#eza-community/eza&Date)

docs: add star history

---

Justfile

build(release): armhf binary

---

Cargo.lock
Cargo.toml
flake.lock

This version includes a fix of an unaligned pointer read.

chore(cargo): bump uzers to v0.11.3

---

Justfile

This helps automating the release process.

build(just): add compression, checksum gen for bin

---

README.md

Refs: https://github.com/eza-community/eza/issues/201

docs(readme): add gentoo

---

Justfile
flake.nix

- test(flake): fix trydump when no files to delete
- build(just): add itest, idump

trycmd via just

---

README.md
man/eza.1.md

Assorted docs: --git-repos & --git-repos-no-status and add gpg armor for .deb pkg

---

README.md

docs(readme): add scoop install info

---

flake.nix

build(flake): make trycmd part of checks

---

.github/workflows/conventional-commits.yml

ci(convco): enforce conventional commits

---

README.md

This Pr is inspired by the issue #308

docs: Added instructions to install completions of eza to the readme

---

Cargo.toml

build(cargo): set optlevel to 3

---

.github/workflows/unit-tests.yml

Put a retry and a timeout on the cargo install command.

tests(actions): stabalised unit-tests.yml

---

.gitignore
Justfile

test(trycmd): autogenerate test dirs

---

completions/bash/eza
treefmt.nix

added the bash completion script to shellcheck

ci: include bash completion script in treefmt

---

README.md

chore: augment gitter size in README

---

README.md

Co-authored-by: Renarde <LanaHeyrendt@gmail.com>
Closes: #348
Refs: #346

fix(fedora): hotfix harmful documentation

---

src/output/file_name.rs

fix(hyperlink): fix hyperlinks on Windows

---

README.md

The Void Linux package has been merged 🎉

docs(readme): add install instructions for Void Linux

---

.github/workflows/unit-tests.yml

ci(unit-tests): fix spelling attemps -> attempts

---

benches/my_benchmark.rs
man/eza.1.md
man/eza_colors-explanation.5.md
man/eza_colors.5.md
src/main.rs
src/options/file_name.rs
src/options/mod.rs
src/options/theme.rs
src/options/vars.rs
src/options/view.rs
src/output/grid_details.rs
src/theme/mod.rs
src/theme/ui_styles.rs

Address issue https://github.com/eza-community/eza/issues/374

feat: Add EZA_ environment variables with fallback to EXA_

---

src/fs/fields.rs
src/fs/file.rs

I do not have a linux box to test on right now.  Someone please test.

fix(fs): Major and minor device on MacOS

---

.git-blame-ignore-revs

fix(git): ignore refs for blame

---

README.md

docs: leave nix install instructions open-ended

---

Justfile

feat(binaries): added statically linked binaries

---

README.md

See: https://github.com/orgs/eza-community/discussions/364

docs(readme): add zsh with homebrew part to completions section

---

Justfile

build(checksums): make checksums easier to copy-paste

---

Justfile

segfaulting on multithreading => need to investigate how to bypass

fix(binaries): diabling static linked binaries due to segfault

---

src/main.rs

fix(main): make os error 13 fail loud

---

Justfile

feat(bin): readded musl static bin as it works

---

Justfile

Fix #458
+ remove extra whitespaces

Direct use of sed|awk commands

---

completions/nush/eza.nu

Add missing nu shell completions I had to remove to make the conversion script work.
The options in questions have choices for which I haven't figured out yet whether nu completions can actually display them, so I left that out.
Resolves #463

feat(completions): add missing nu shell completions

---

man/eza.1.md
src/options/vars.rs
src/options/view.rs

This var will override any --git or --git-repos
closes #495

feat(git): adding the EZA_OVERRIDE_GIT env var

---

completions/fish/eza.fish
completions/nush/eza.nu
completions/zsh/_eza

Contains additional completions missed in #503.
Resolves #511

fix: update additional completions for help, almost-all, dereference

---

completions/zsh/_eza

fix(completions): fix zsh completions

---

completions/bash/eza
completions/fish/eza.fish
completions/nush/eza.nu
completions/zsh/_eza
man/eza.1.md
src/options/flags.rs
src/options/help.rs
src/options/view.rs
src/output/render/groups.rs
src/output/table.rs

feat: add option --smart-group

---

src/output/render/groups.rs
src/output/table.rs

fix: --smart-group only works for current user

---

src/output/grid.rs
src/output/grid_details.rs

fix spacing issue for --no-quotes

---

.github/CODEOWNERS

to make sure I get ping'd on files being touched. this whole width/grid issue has pretty much fallen on me so i've spent many hours in these files.

chore: add to CODEOWNERS file 

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
CONTRIBUTING.md
README.md

docs: improve CONTRIBUTING.md, README.md

---

src/info/filetype.rs
src/output/icons.rs

PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement.
https://prql-lang.org/
https://github.com/PRQL/prql

feat: Add PRQL

---

src/main.rs
src/options/flags.rs
src/output/details.rs
src/output/grid_details.rs
src/output/table.rs
tests/cmd/long_git_repos_nix.stdout
tests/cmd/long_git_repos_no_status_nix.stdout

Repo column was always showing even tho no repo was here see eza-community/eza#579 first point

fix(git)!: remove Repo column when using --git-repos when no git repo

---

flake.nix

fix(build): fix cross compilation

---

src/options/flags.rs

Base value is set to all
fixes #634

fix(flags): colo[u]r-scale didn't have a base value

---

.git-blame-ignore-revs

chore(git): ignore blame from #644

---

src/options/vars.rs

Implemented var mocking in order to sue in tests, especially clap tests

test(vars): Vars mocking

---

flake.lock

I just bumped semnix versions, and thus it felt fitting to bump our flake inputs as well.
`just itest`, but of course :p

chore(flake): update flake inputs

---

src/fs/file.rs
src/output/color_scale.rs

fix: crashing bugs #655 and #667

---

.gitignore
README.md
completions/fish/eza.fish
completions/nush/eza.nu
completions/zsh/_eza
man/eza.1.md
src/main.rs
src/options/flags.rs
src/options/help.rs
src/options/mod.rs
src/options/stdin.rs
src/options/vars.rs
tests/gen/ptest_2439b7d68089135b.stdout
tests/ptests/ptest_2439b7d68089135b.stdout

This pr is aiming at making available argument streaming

Add piping of arguments

---

tests/gen/ptest_a82ad7ec2e961f84.stdout
tests/gen/ptest_af29d370729835d8.stdout
tests/ptests/ptest_a82ad7ec2e961f84.stdout
tests/ptests/ptest_af29d370729835d8.stdout

I suppose these should be regenerated as part of the release process... I'll do
that eventually...

test(powertest): fix version tests

---

src/output/render/size.rs
src/theme/default_theme.rs

Fixing some color scales error
closes #414 
closes #682 
closes #684

Fixing color scale errors

---

man/eza.1.md
man/eza_colors.5.md
src/fs/fields.rs
src/fs/file.rs
src/options/flags.rs
src/options/help.rs
src/options/vars.rs
src/options/view.rs
src/output/render/flags.rs
src/output/render/flags_bsd.rs
src/output/render/flags_windows.rs
src/output/render/mod.rs
src/output/table.rs
src/theme/default_theme.rs
src/theme/mod.rs
src/theme/ui_styles.rs
tests/gen/ptest_2439b7d68089135b.stdout
tests/ptests/ptest_2439b7d68089135b.stdout

Add BSD file flags.  See the man page for chflags(1).

feat(flags): Add BSD file flags

---

Justfile
flake.nix

closes: #674 
BREAKING_CHANGE:
Adding blake3 nees b3sum as a dependency

chore(checksum): adding blake3 to checksums

---

flake.nix

Worked fine on my machine and `nix flake check` passes (if I merge this)

build(flake): add cargo-bump for releasing

---

tests/ptests/ptest_a82ad7ec2e961f84.toml
tests/ptests/ptest_af29d370729835d8.toml

fix(tests): remove version testing

---

flake.lock
flake.nix

build(flake): change flake inputs

---

completions/zsh/_eza

fix(completions): fix total-size option

---

Justfile

fix: build aarch64, arm without libgit2

---

INSTALL.md

fix: fixed typo in INSTALL.md

---

.github/workflows/unit-tests-bsd.yml

Update FreeBSD version in CI to `14.1`.

build: bump FreeBSD version.

---

src/fs/file.rs

`NaiveDateTime`'s `From<SystemTime>` impl panics on extreme time values. Copying from what `changed_time` does, use `NaiveDateTime::from_timestamp_opt` which will return `None` instead of panicking.
Perhaps all of this could use a refactor, since `NaiveDateTime::from_timestamp_opt` is deprecated since chrono 0.4.35, but seeing as it's already being used here I elected to use it too.
Fixes: #655

fix: crash in #655

---

.github/workflows/unit-tests-bsd.yml

fix: disable broken freebsd tests

---

src/logger.rs

fix: logger typo

---

Cargo.lock
Cargo.toml
src/output/mod.rs

build(deps): bump windows-sys from 0.52.0 to 0.59.0

---

deny.toml

fixes audit regression introduced in #840 by introducing MPL-2.0

ci: allow MPL-2.0

---

Justfile

Users where confused why the changelogs included releasing eza, which is fair.
Instead, I've changed the message to reflect what the commit actually does,
making it more clear.
It will be tested on the next release.

docs: better version bump commit summary

---

.github/workflows/conventional-commits.yml
.github/workflows/no-merge-commits.yml

fix(ci): split commits workflows and run no-merge-commits only on PRs

---

INSTALL.md

docs(install): cargo install dir inaccurate

---

flake.nix

fix: release recipe

---

man/eza.1.md

Remove stray description (originally from --decay-mode). Fixes #1255

---

Cargo.lock
Cargo.toml

refactor: just a new crate name so we can republish this
I'm not sure we really even want this as a separe crate, it's pretty
small... that said, it's trivial to maintain.
Regardless, I'm more comfortable with it being on a committers account,
given this has seen any activity in 9 years. We can decide to do
something intelligent later.

build(deps): we switch to our own fork of natord

---

Cargo.lock
flake.lock

- **build(deps): update flake inputs 2025-01-08**
- **build(deps): update cargo inputs 2025-01-08**

flake/cargo bump 2025-01-08

---

Cargo.lock
flake.lock
flake.nix

- **build(deps): cargo bump 2025-01-16**
- **build(deps): flake bump 2025-01-16**

build(deps): bump dependencies

---

Cargo.lock
flake.lock

- **build(deps): cargo bump 2025-01-23**
- **build(deps): flake bump 2025-01-23**

flake/cargo bump 2025-01-23

---

src/options/config.rs
src/options/theme.rs

closes #1356 
that was my fault, this could have been simplified quite a bit.

fix: regression in theme config location, simplify path

---

Cargo.lock
flake.lock

- **build(deps): bump flake**
- **build(deps): bump cargo**
Bumps cargo and flake deps
`nix flake check`

flake/cargo bump 2025-01-29

---

src/output/icons.rs

fix(icons): make `flake.lock` icon the nix logo

---

src/output/icons.rs

chore: add icon for *.hrl

---

src/output/icons.rs

chore: add photoshop icon for *.psb

---

src/output/icons.rs

chore: add eslint icon for .eslintignore

---

src/output/icons.rs

chore: add renovate icon for renovate.json

---

src/output/icons.rs

feat(icons): add `.exercism` folder icon

---

src/output/icons.rs

feat(icons): add `.ocamlinit` icon

---

src/output/icons.rs

chore: add gcloud icon for .gcloudignore

---

.github/dependabot.yml
Cargo.lock
Cargo.toml
flake.lock
rust-toolchain.toml
src/fs/fields.rs
src/fs/file.rs

- **fix(deps): flake bump 2025-03-20**
- **build(deps): cargo deps 2025-03-20**

update the deps and such

---

src/output/icons.rs

chore: add markdown icon for *.mdx

---

Cargo.lock
flake.lock

- **build(deps): flake bump 2025-04-19**
- **build(deps): cargo bump 2025-04-19**

bumps 2025 04 19

---

.config/treefmt.nix
Cargo.lock
flake.lock
src/fs/feature/git.rs
src/options/mod.rs
src/output/render/blocks.rs

- **build(deps): cargo bump 2025-05-01**
- **build(deps): flake bump 2025-05-01**

build(deps): bump cargo/flake deps

---

src/output/escape.rs
src/output/file_name.rs

Some terminal emulator do it themselves, but we want to be correct everywhere
Fix #1230 
Also move code around to add a test, because this is not the first time we have a regression on that feature.

fix(hyperlink): escape spaces in file path to make them work correctly

---

src/fs/feature/git.rs

Fix #445
We can’t convert from libgit2’s bytes to `OsStr` on Windows, so at least we ignore paths with incorrect Unicode instead of crashing.
Note: I didn’t try on Windows so I couldn’t test it.

fix(git): ignore incorrect Unicode path instead of crashing on Windows

---

src/output/icons.rs

chore: add Visual Studio icon for *.suo

---

src/output/icons.rs

chore: add swift icon for *.xcplayground

---

src/output/icons.rs

chore: add dropbox icon

---

.github/workflows/unit-tests.yml
src/fs/dir.rs
src/fs/feature/git.rs
src/fs/feature/xattr.rs
src/fs/file.rs
src/info/sources.rs
src/main.rs
src/options/parser.rs
src/options/vars.rs
src/options/view.rs
src/output/color_scale.rs
src/output/details.rs
src/output/file_name.rs
src/output/grid.rs
src/output/render/permissions.rs
src/output/table.rs
src/theme/lsc.rs
src/theme/mod.rs
src/theme/ui_styles.rs

Let’s see if that fix our little issue with OpenBSD in the CI.

fix(ci): use OpenBSD 7.7 that has MSRV, instead of 7.6

---

Cargo.lock
flake.lock

Bumps flake and cargo deps.
CI activity.

build(deps): flake + cargo

---

Cargo.lock
flake.lock

- **build(deps): cargo bump 2025-07-03**
- **build(deps): flake bump 2025-07-03**

build(deps): update flake/crate deps

---

src/fs/file.rs

e3c5fa745b29b14e9b2b5c96167e20fda3ec845c removed the unsafe blocks for libc::major and libc::minor after the libc crate inlined the macros they are defined as on most platforms. On illumos and Solaris, the libc crate still calls the C binding, so this change broke compilation there. Add back the unsafe blocks, and allow the unused_unsafe lint for the vast majority of platforms where it would apply.

fix(file): restore unsafe blocks for libc major/minor device id

---

Cargo.lock
flake.lock

- **feat: update flake inputs**
- **build(deps): update cargo deps**

build(deps): flake + cargo updates

---

Cargo.lock
flake.lock

fetching git input 'git+file:///home/ces/org/src/git/eza'
warning: Git tree '/home/ces/org/src/git/eza' is dirty
fetching github input 'github:rustsec/advisory-db'
fetching github input 'github:numtide/flake-utils'
fetching github input 'github:nix-community/naersk'
fetching github input 'github:NixOS/nixpkgs/nixpkgs-unstable'
fetching github input 'github:eza-community/powertest'
fetching github input 'github:cachix/pre-commit-hooks.nix'
fetching github input 'github:oxalica/rust-overlay'
fetching github input 'github:nix-systems/default'
fetching github input 'github:numtide/treefmt-nix'
warning: updating lock file '/home/ces/org/src/git/eza/flake.lock':
• Updated input 'advisory-db':
'github:rustsec/advisory-db/c8fa947b3cb681ce18c6a44a42382c45ac13f30e' (2025-09-12)
→ …

fix: update nixpkgs/cargo dependencies
