- README.md
- completions/fish/exa.fish
- completions/zsh/_exa
- man/exa.1.md
- src/fs/feature/xattr.rs
- src/fs/fields.rs
- src/fs/file.rs
- src/options/flags.rs
- src/options/help.rs
- src/options/view.rs
- src/output/details.rs
- src/output/grid_details.rs
- src/output/render/mod.rs
- src/output/render/permissions.rs
- src/output/render/securityctx.rs
- src/output/table.rs
- src/theme/default_theme.rs
- src/theme/mod.rs
- src/theme/ui_styles.rs
https://github.com/ogham/exa/pull/855
> (exa PR) 855:  Add option to show security attribute and improve extended support

- src/output/table.rs
https://github.com/ogham/exa/pull/981
> (exa PR) 981: Don't show an error on stdout when there is no timezone info

- README.md
- completions/fish/exa.fish
- completions/zsh/_exa
- man/exa.1.md
- src/options/file_name.rs
- src/options/flags.rs
- src/options/help.rs
- src/output/file_name.rs
- src/output/grid.rs
https://github.com/ogham/exa/pull/1177
> (exa PR) 1177: feature: hyperlink flag

- .github/workflows/unit-tests.yml
This should re-enable the CI workflow, for some reason the last attempt was buggy.
> ci: Create unit-tests.yml

- src/output/icons.rs
https://github.com/ogham/exa/pull/1051
> (exa PR) 1051: changed default folder icon

- flake.nix
- rust-toolchain.toml
- treefmt.nix
Tracking issue: #72 
- remove a bunch of whitespace
- check nix files' formatting
- run test suite with `nix flake check`
- run `cargo test` when building via flake to ensure working output
- add clippy as part of the toolchain
> Flake improvments

- src/output/icons.rs
https://github.com/ogham/exa/pull/1199
> (exa PR) 1199: Added icons for .rmeta and .ino files

- .github/workflows/unit-tests.yml
https://github.com/ogham/exa/pull/1188
> (exa PR) 1188: Moving actions to dtolnay's version

- snap/snapcraft.yaml
This changes the name in the snapcraft.yaml file to eza
> fix: update snapscraft.yaml

- flake.nix
Closes #86
Very simple fix. A lot of programs need those dependencies specified when building with nix for macOS.
Though what's interesting is I cannot reproduce that issue on latest main but I know I had that issue many times and upstream nixpkgs also defines these to be dependencies needed for building.
> fix: macOS flake support

- build.rs
- src/fs/feature/git.rs
- src/fs/fields.rs
- src/fs/file.rs
- src/fs/filter.rs
- src/logger.rs
- src/main.rs
- src/options/error.rs
- src/options/filter.rs
- src/options/help.rs
- src/options/parser.rs
- src/options/theme.rs
- src/options/view.rs
- src/output/cell.rs
- src/output/details.rs
- src/output/file_name.rs
- src/output/grid.rs
- src/output/grid_details.rs
- src/output/render/git.rs
- src/output/render/octal.rs
- src/output/table.rs
- src/output/time.rs
- src/theme/mod.rs
I handled all clippy lints. This makes `nix flake check` pass, and allows further work to add clippy to CI.
This will increase code quality.
This should make the code more readable and easier to use, and currently we are
at a reasonable time with not that many open pull requests (that I expect will get merged).
Rather now than in a few weeks, if the new PR trend is growing at a constant rate.
Using `cargo test`, `nix flake check`, `nix build ./#clippy`, now CI tests as well.
- [-] Have you added adequate tests?
- [?] Does your code pass CI tests?
- refactor(clippy): fix borrowed trait implements required
- refactor(clippy): simplify format strings
- refactor(clippy): consistent style
- refactor(clippy): clippy::explicit_auto_deref
- refactor(clippy): clippy::explicit_auto_deref
- …
> Make Nix Flake Check Pass

- src/fs/feature/git.rs
This PR fixes the `GIT_DIR`-related issues mentioned in #115, and also adds support for `GIT_CEILING_DIRECTORIES`.
(Normally I'd do those two things in separate PRs, but every line that the latter changes is also changed by the former - I put them in separate commits though, so unless you squash when merging, they'll stay as cleanly separated atoms of change in the history.) 
`GIT_CEILING_DIRECTORIES` is actually my main goal here. I depend on Git's ceiling directory feature every day to keep a lot of my `(exa|eza) --long --git ...` invocations from freezing up (for 2-3 seconds at a time in the worst case). So I had done that change first (a couple days ago, after I realized that [my PR to the Exa upstream](https://github.com/ogham/exa/pull/1228) probably wasn't going to move), then while …
> Fix+improve Git repository lookup (`GIT_DIR`; `GIT_CEILING_DIRECTORIES`)

- completions/zsh/_eza
With the current build I get errors when I try to call the tab-completion for `eza` from zsh:
```shell
$ eza
_arguments:comparguments:327: invalid argument: {-o,
_arguments:comparguments:327: invalid argument: {-o,
_arguments:comparguments:327: invalid argument: {-o,
```
This PR fixes the slight typo in the completion file that causes this error.
> fix: Broken zsh completion syntax

- README.md
- completions/fish/eza.fish
- completions/zsh/_eza
- man/eza.1.md
- src/options/flags.rs
- src/options/help.rs
- src/options/view.rs
`ls` has a `-w/--width` option limiting the columns of the grid output. `exa/eza` only allows to specify the number of columns via the `COLUMNS` environment variable for some reason.
This adds the `-w/--width` option to the existing column limiting, meaning it behaves just like when specifying the `COLUMNS` variable, but with the `ls`-like command line argument. In case both `COLUMNS` and `-w`, then the cli option takes precedence.
The only difference to the `-w` option of `ls` is, that `ls -w 0` sets the columns to infinity, while here it goes back to automatic width detection just as for the `COLUMNS` variable.
Resolves https://github.com/ogham/exa/issues/1168
> Add Width Option

- .envrc
- .gitignore
I use and like [direnv](https://direnv.net) because it saves me from needing to always run `nix develop...`
The file shouldn't do anything for ppl that don't have direnv installed so it's a harmless addition but positive imo
> Add `.envrc` so direnv automatically opens the nix dev environment

- man/eza_colors.5.md
- src/theme/ui_styles.rs
I tried to specify colors of ignored git files, and then saw that it was an issue on the exa page. Turns out it was an incredibly trivial fix :smile:
So I see some recent activity on the exa page, but either way I am glad to see community stepping up to maintain this project, and I will definitely do my part as a long time exa user to contribute to which ever project.
> added git-ignored color/style option

- src/output/grid_details.rs
The hyperlink option adds an escape sequence (https://github.com/eza-community/eza/blob/main/src/output/file_name.rs#L325-L329) which in the normal TextCell creation also becomes part of the length calculation. This patch applies the same logic the normal grid already did (https://github.com/eza-community/eza/blob/main/src/output/grid.rs#L45-L58), by using the filenames bare width when a hyperlink is embedded. It also respects the ShowIcons option just like the normal grid view.
Resolves #129
> Fix Hyperlink Details Grid Bug

- Cargo.toml
- README.md
- build.rs
- man/eza.1.md
- man/eza_colors.5.md
This repository was transferred from `cafkafk` to `eza-community` (https://github.com/ogham/exa/issues/1139#issuecomment-1664997468)
This PR replaces all remaining references to the old repository.
> docs: cafkafk -> eza-community

- README.md
- completions/fish/eza.fish
- completions/zsh/_eza
- man/eza.1.md
- src/options/flags.rs
- src/options/help.rs
- src/options/view.rs
- xtests/outputs/help.ansitxt
This PR adds the `--no-git` option. This option overrides `--git` in all cases and disables showing the Git status of files in long view (`-l`). This enables users of shell aliases and the like to turn off git status display in an *ad hoc* manner.
It might someday be worth looking into automatic `--no-`-prefixed versions of flags, but for now, this works.
(This is my first contribution to this codebase; I've done my best to make all the appropriate changes, but I'd appreciate any pointers if there's something I've missed. I took inspiration from the `--no-icons` option as prior art.)
> Add --no-git option

- src/options/help.rs
Before:
```
FILTERING AND SORTING OPTIONS
-a, --all                  show hidden and 'dot' files
-d, --list-dirs            list directories as files; don't list their contents
-L, --level DEPTH          limit the depth of recursion
-r, --reverse              reverse the sort order
-s, --sort SORT_FIELD      which field to sort by
--group-directories-first  list directories before other files
-D, --only-dirs            list only directories
-I, --ignore-glob GLOBS    glob patterns (pipe-separated) of files to ignore
--git-ignore             ignore files mentioned in '.gitignore'
Valid sort fields:         name, Name, extension, Extension, size, type,
modified, accessed, created, inode, and none.
date, time, old, and new all refer to modified.
```
After:
```
FILTERING AND SORTING OPTIONS …
```
> Re-align `--git-ignore` line in help message

- src/fs/file.rs
On a unix system a directory will have a link count of two when it does not have any subdirectories.  This adds a check to `is_empty_dir` to check the link count to avoid the expensive listing of a directory.
Also noticed there is not a windows version of `is_empty_dir` so eza will most likely not compile on windows.  I am not a windows developer and have no way to build or test a windows version.
> feat: Optimize checking for empty directories when a directory has subdirectories

- .envrc
If someone’s using `direnv` but has not `nix` installed, either you don’t allow the `.envrc` and you get `direnv: error /home/ariasuni/projets/contrib/eza/.envrc is blocked. Run `direnv allow` to approve its content`, or you allow it and get `environment:1270: nix : commande introuvable`, everytime you enter the directory.
As an alternative, use a condition so that direnv doesn’t try to use nix if it’s not installed.
> Avoid error messages if direnv is installed but nix isn't

- .github/workflows/unit-tests.yml
- src/fs/feature/git.rs
- src/fs/feature/xattr.rs
- src/fs/fields.rs
- src/fs/file.rs
- src/options/parser.rs
- src/options/theme.rs
- src/output/render/links.rs
- src/output/render/mod.rs
- src/output/render/permissions.rs
- src/output/table.rs
- src/theme/mod.rs
I don't have a Mac to test on, I'd appreciate it if someone could check that build out too. This branch currently builds on both Windows and Linux.
Fixes #169 
Fixes #102
> Tree-wide: Fix Windows build

- Cargo.toml
This builds libgit2 into the binary to avoid dependency problems on systems that don't have the required version of libgit2 yet.
When building the deb package from eza tag v0.11.0 and installing it you run into this problem:
I'm not exactly sure why this didn't appear before and how we got into this, but my best guess is this https://github.com/eza-community/eza/pull/182 where be bumped the https://github.com/rust-lang/git2-rs/ version. Somehow the new version requires the `vendored-libgit2` feature to be set to ship libgit2 with it and before it didn't, although I can't really tell where from their changelog.
You might wonder why don't we just add this as dependency to our deb package ... well, neither the newest Ubuntu nor Debian have the required libgit2 v1.7 in their repos but only …
> Add vendored-libgit2 feature to git2 dependency

- Cargo.lock
- Cargo.toml
- src/info/filetype.rs
- src/logger.rs
- src/main.rs
- src/output/cell.rs
- src/output/details.rs
- src/output/escape.rs
- src/output/file_name.rs
- src/output/grid_details.rs
- src/output/icons.rs
- src/output/lines.rs
- src/output/render/blocks.rs
- src/output/render/filetype.rs
- src/output/render/git.rs
- src/output/render/groups.rs
- src/output/render/inode.rs
- src/output/render/links.rs
- src/output/render/octal.rs
- src/output/render/permissions.rs
- src/output/render/securityctx.rs
- src/output/render/size.rs
- src/output/render/times.rs
- src/output/render/users.rs
- src/theme/default_theme.rs
- src/theme/lsc.rs
- src/theme/mod.rs
- src/theme/ui_styles.rs
newly maintained ansiterm over at [rustadopt](github.com/rustadopt)
Much cleaner/nicer PR than before as we no longer need to change `colour` -> `color` etc. and the API is totally unchanged.
> deps: change ansi_term to ansiterm from rustadopt

- Cargo.lock
- Cargo.toml
- README.md
- completions/fish/eza.fish
- completions/zsh/_eza
- man/eza.1.md
- man/eza_colors.5.md
- src/fs/file.rs
- src/fs/mod.rs
- src/fs/mounts.rs
- src/main.rs
- src/options/flags.rs
- src/options/help.rs
- src/options/view.rs
- src/output/details.rs
- src/output/file_name.rs
- src/output/lines.rs
- src/theme/default_theme.rs
- src/theme/mod.rs
- src/theme/ui_styles.rs
From https://github.com/ogham/exa/pull/941
In grid view underlines directories which have filesystems mounted on them.
In long view displays the mounted filesystem and type.
Couple of questions:
- I'm happy with the underline for denoting a mounted fs, but the long format looks a bit weird. Does anyone have better suggestions how to format it?
- Should the long view details be enabled by an option?
The original `exa` PR also had a `btrfs` subvolume feature but I'll implement that on top of this one once accepted. Same two questions will go for that one as well.
> Add mounted filesystem info

- Cargo.lock
- Cargo.toml
- src/output/escape.rs
- src/output/file_name.rs
Follow-up of #17.
Fix #162.
Other bugs fixed/improvements:
- Take control characters outside of ASCII into account (by using [`char::is_control`](https://doc.rust-lang.org/std/primitive.char.html#method.is_control)).
- Hyperlink are now appearing on filenames with escaped characters
- Deduplicated the escaping code by replacing the original code with the optimized one (that I very slightly improved).
> fix: filename escaping (last character lost sometimes, no hyperlink)

- Cargo.toml
- devtools/deb-package.sh
I exposed the `vendored-libgit2` feature as suggested and altered the `deb-package.sh` script to include the corresponding build commands.
Resolves #214
> Expose vendored libgit2

- src/theme/default_theme.rs
- src/theme/lsc.rs
[I know it's not much of a difference.. but it might be more visible]
After many of these such issues: https://github.com/eza-community/eza/issues/234
I figured it was time to add some of the updates that we merged into the newly maintained ansiterm at [rustadopt](https://github.com/rustadpot/ansiterm-rs)
Some of which, are the option for bright colors on terminals that support it. I know that it's a bad picture, but it's possible that these dashes will show up on lighter terminals. If not, the default color can be changed on something we agree on (one of them may very well be a new brighter one)
I still have to add into the documentation / man-pages that we support bright colors 90 - 108
> feat: add bright colour options, change punctuation default

- Cargo.lock
- Cargo.toml
- build.rs
- src/fs/file.rs
- src/output/render/times.rs
- src/output/table.rs
- src/output/time.rs
> Use chrono

- completions/fish/eza.fish
- completions/zsh/_eza
- src/options/help.rs
- xtests/outputs/help.ansitxt
Fixes my complaint in https://github.com/eza-community/eza/issues/238.
Copied the expanded info from the manpage file.
> fix: expand `--all` help

- .github/workflows/audit.yml
- Cargo.lock
- Cargo.toml
- deny.toml
This runs `cargo deny check` every night. ... This is similar but more extensive to running `cargo audit` locally.
> feature(ci): add audit workflow

- .gitignore
- devtools/deb-package.sh
Since we are now shipping three linux architectures I thought I automate the process for the deb packages just a little bit more with my script and ended up over-engineering it completely.
It now automatically checks out the most recent tag, loops over the three architectures, pulls the corresponding binary asset from the release page and verifies that the checksum is present in the release notes, and then builds the corresponding package, leaving me with three .deb files I can just scp to the repo host. :rocket: 
@cafkafk this assumes that the assets have a name of the form `eza_{{ target }}.tar.gz` and that the corresponding md5sum is somewhere present in the release notes.
> Revise deb package script

- CONTRIBUTING.md
Since it took me a moment to notice and grasp it myself how commit messages were altered on my PRs, I though I'd add some guidelines to `CONTRIBUTING.md` so contributors already try to use the wanted format and maintainers don't have to edit every single commit.
Feel free to adjust it! I was just guessing these from my experience.
> Add guidelines for commit messages

- README.md
Deamoring seems to break the installation on some normal Debian system while the only reported issue without it was in a Ubuntu Docker container. Thus we should not recommand dearmoring but only mention it for containers as edge cases.
Resolves #259
> fix(readme): revert to old apt install command suggestion and add hint

- README.md
OpenSUSE builds the `eza` (and the shell completion packages) RPMs; documenting how to install those on two RPM-based distros.
> feat: Document installing eza on RPM-based distributions

- .github/workflows/apt.yml
- .github/workflows/unit-tests.yml
This adds a workflow that every night and on changes to the gpg key or this workflow installs eza from the deb repo and runs it and opens the man page to verify that the deb repo is working correctly.
I also limited the unit-tests workflow to run on unit-tests workflow changes instead of all workflow changes as this seems like an overkill.
> feat(ci): add apt installation workflow

- completions/bash/eza
[Grep 3.8 causes warnings on regular expressions with stray backslashes:](https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html)
> Regular expressions with stray backslashes now cause warnings, as
> their unspecified behavior can lead to unexpected results.
> For example, '\a' and 'a' are not always equivalent
> <https://bugs.gnu.org/39678>... The warnings are intended as a
> transition aid; they are likely to be errors in future releases.
On a fresh Fedora 38 container with grep 3.8, this results in warnings showing up in the terminal when trying to use the bash completions:
I can't say *why* these particular backslashes are stray backslashes, but removing them results in the completions working without any errors:
> fix(completions): remove stray backslashes

- src/fs/dir.rs
Reverts eza-community/eza#225
as pointed out by @cfxegbert on element, is_ok_and was first stabilized in 1.70 (https://github.com/rust-lang/rust/pull/110019), but we have to support 1.65 for gentoo, so unfortunately this will have to be reverted temporarily
> Revert "Support for Windows Hidden Files"

- devtools/deb-package.sh
- treefmt.nix
I was just looking around in the codebase and got some warnings from shellcheck when opening this file. 
This is still a draft since I want to to see the CI/CD checks first and test rather the script still works through manually testing it.
As soon as I tested it I will convert the draft to a normal pull request.
> fixed shellcheck warnings and added shellcheck to treefmt

- src/fs/dir.rs
- src/fs/file.rs
- src/main.rs
- src/output/details.rs
> fix(file): exit 13 on os error 13

- .github/workflows/winget.yml
- README.md
- Resolves #298
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @eza-community. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.
If you want to see an example of a PR created using this action, see …
> ci: add Winget Releaser workflow

- .github/workflows/flake.yml
The nix flake check Command Tests rather the nix package builds in all supported systems and checks formatting.
This is a follow up to #293. There I was stating that shellcheck is executed through github actions which is not the case because of only running nix build.
> Added nix Flake check to flake.yml

- src/fs/dir.rs
Adds an extra check on attributes().hidden on Windows. This hides Windows hidden files whenever dot files are also filtered out
Resolves #212
See #225 for context, this was reverted due to concerns over `is_ok_and` in Rust 1.65, but the minimum supported version has been bumped to 1.70 (see #313)
> feat: Adds filtering for Windows hidden files

- Cargo.lock
- Cargo.toml
- benches/my_benchmark.rs
- src/lib.rs
This PR adds a MVP for benchmarking code and generating reports about performance. In order to do this, it was nescesarry to add `lib.rs`. Also, currently, there is a duplication of the mount lazy_static from main.
> perf(criterion): add criterion for benchmarking

- flake.nix
I mentioned that nix flake check would also build the default package. This is not the case as I found out today reading the mane page of `nix flake check` more carefully. In order to also build the default package It has to be added to the checks. **Or** nix build should be added back to the workflow.
@cafkafk Is it a better solution to make `nix flake check` also build the package or add back `nix build`?
`nix flake check` takes way longer.
every supported target will be tested.
Again sorry for missunderstanding the docs and stating that `nix flake check` would build even tho it doesn't.
> fix: nix flake check also builds the package

- README.md
trusted.gpg.d requires de-armored keys on some systems (Ubuntu 20.04) and ASCII-armored keys on others (Debian 12)
this keyring method works on both systems. I tested in an ubuntu:20.04 container and a debian:12 container
it also uses `dd of=` instead of `tee` to avoid dumping binary to the terminal
fixes #259
> docs(readme): Update deb instructions to use keyring

- Cargo.toml
- deny.toml
- rust-toolchain.toml
- snap/snapcraft.yaml
- treefmt.nix
- yaml: for GitHub Actions
- toml: for Rust configs mainly (I can change the style if there's an issue with the default style of the formatter) 
- deadnix: detecting dead nix code (@cafkafk should I remove it or is there use for this?)
I in my opinion part of making a codebase easy to navigate is proper formatting and the cost of CI time is not that high. But I still get why many think formatters are not needed for configuration files.
@cafkafk the toml style is different from what we currently use. Is the style using the formatter fine or is.
```toml
exclude = ["/devtools/*", "/Justfile", "/Vagrantfile", "/screenshots.png", "/tests"]
```
```toml
exclude = [
"/devtools/*",
"/Justfile",
"/Vagrantfile",
"/screenshots.png",
"/tests",
]
```
deadnix is really useful when having a bigger nix …
> Treefmt for configs (.toml, .yaml)

- .github/workflows/apt.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/flake.yml
- .github/workflows/label.yml
- .github/workflows/stale.yml
- .github/workflows/unit-tests.yml
- Use the action Swatinem/rust-cache@v2 as it caches previously used
dependencies, which helps save a lot of time.
- remove secrets.GITHUB_TOKEN as it's available by default.
- Use Github Actions concurrency feature, which will cancel previous
jobs from a PR if it's been updated.
> ci: make various improvements

- Cargo.lock
- Cargo.toml
- src/output/file_name.rs
Follow-up of #352 
- Remove the hostname part of the `file://` URL because it probably won’t work with some host/DNS configs, and doesn’t work at all in Konsole.
- Respect the spec on Windows by URL encoding the path (needs test!!)
- Replace `urlencoding` by [`percent-encoding`](https://crates.io/crates/percent-encoding) which is more ergonomic (and I trust it’s fast and reliable because it comes from Servo)
> fix(hyperlink): respect spec on Windows and make it for with Konsole

- .github/workflows/label.yml
The problem with the default behavior is that it's simply too
aggressive. It will re-apply a label that a maintianer have removed
every time the PR is updated, making it impossible to manually adjust
labels that doesn't fit exactly according to the labeler rules.
> ci: only apply labels when opening a PR

- src/fs/feature/git.rs
- src/fs/fields.rs
- src/output/render/git.rs
- src/output/render/mod.rs
- src/output/table.rs
- src/theme/default_theme.rs
- src/theme/mod.rs
- src/theme/ui_styles.rs
- tests/cmd/long_git_repos_no_status_nix.stdout
Fix #391
In the end, I find that the way traits are used for this is pretty elegant.
A `trait` is used to define a set of functions, each returning a `Style` for a particular element or type of element. This trait is implemented on `Theme`, and when we pass around the actual theme, we cast it to a particular `trait` in a particular render function, which means we can only use the `Style`s returned by the functions of the trait.
Also I changed the colors to use the terminal theme, and now the status column don’t even appear if we use `--git-repos-no-status`.
Result:
> fix(git-repos): don’t show color when color is disabled

- rustfmt.toml
- src/options/flags.rs
This prevents most LSP's/Editors that will auto run rustfmt on save. Most do not respect the .nix file, so this will keep `flags.rs` from getting formatted each time someone contributes.
> feat: add rustfmt.toml file to prevent flags.rs fmt on save

- completions/fish/eza.fish
- completions/zsh/_eza
- man/eza.1.md
- src/main.rs
- src/options/file_name.rs
- src/options/flags.rs
- src/options/help.rs
- src/output/escape.rs
- src/output/file_name.rs
https://github.com/eza-community/eza/issues/311
the commit history was a mess on the original PR, and its time to revisit this :D 
feedback/testers needed
> feat: add quotations around filenames with spaces. exa pr#1165

- Justfile
- flake.nix
- man/eza.1.md
- man/eza_colors-explanation.5.md
- man/eza_colors.5.md
At the moment the `eza.1` and `eza_colors.5` manpages show the hardcoded and outdated version v0.9.0, and `eza_colors-explanation.5` doesn't show any version and doesn't even have a header at all.
This adds the missing header and replaces the hardcoded version strings by `$version` which is then replaced in the `@man` rule by the version set in `Cargo.toml`. It also refactors the rule to use a for loop instead of three separate pandoc commands.
> Dynamic Manpage Version

- README.md
as eza is now on termux we needed to add it to documentation
closes #366
> docs(installation): adding termux section

- Cargo.lock
- Cargo.toml
- README.md
- completions/bash/eza
- completions/fish/eza.fish
- completions/zsh/_eza
- man/eza.1.md
- src/main.rs
- src/output/mod.rs
`terminal_size::terminal_size()` is used to determine if stdout is connected to a real tty/pty. In previous version of `terminal-size`, this method only queries the terminal size for `stdout`. However, it is changed in the following commit
https://github.com/eminence/terminal-size/commit/08f0e73926c11adc3105dbf4eb84dd8c9e6c873a Now the method will use `stdout, stdin, stderr`, trying its best to determine the terminal size. This cannot be used to determine if `eza` output is piped or redirected.
We should use `terminal_size_using_fd` on `stdout.as_raw_fd` instead.
This patch makes `eza --color=auto` behaves like `ls --color=auto`.
Resolves #434 Fixes #433
Also Resolves #441 as well.
> fix: query stdout terminal size to see if the output gose to a tty.

- .github/CODEOWNERS
- completions/nush/eza.nu
This adds an initial nushell completion file generated with https://github.com/dscottboggs/nu-completions from our fish completions ... I had to remove a few things to make it work. The script doesn't like `\` and multiline strings. Maybe we can add those manually after verifying that this at least works.
Resolves #254
> feat(completions): add basic nushell completion file

- src/output/file_name.rs
- src/output/grid.rs
- src/output/grid_details.rs
This addresses #446 
About the type change: It came up because `String::repeat` expects `usize`.
But all the other places using the field are already converting anyway so it was a no-brainer to change it in my opinion
> Don't match for numbers and remove single-use fn

- Cargo.toml
`opt-level = 3` is the default for release builds (https://doc.rust-lang.org/stable/book/ch14-01-release-profiles.html).
`codegen-units = 1` lengthens the build by about 4 seconds on my system and produces a ~20KiB smaller binary.
> build: add `codegen-units = 1`

- README.md
The eza update is [partially available on stable](https://bodhi.fedoraproject.org/updates/?packages=rust-eza). The rest of the packages will be fully available within 5 days.
The full package is under the name [rust-eza](https://packages.fedoraproject.org/pkgs/rust-eza/), being [eza](https://packages.fedoraproject.org/pkgs/rust-eza/eza/) a subpackage of it.
I tested the version in the testing channel and it works ok in fedora 38.
I want to clarify that I had nothing to do with bringing the package to fedora, I just leave my contribution by updating the readme. Many thanks to those who made it possible.
> docs(readme): installation on fedora updated

- devtools/deb-package.sh
This changes the target for the `amd64` deb package to `x86_64-unknown-linux-musl`. I have been using this for a few releases already but haven't commited it yet.
> refactor(devtools): use musl target for amd64 deb package

- completions/bash/eza
- completions/nush/eza.nu
- completions/zsh/_eza
- man/eza.1.md
- src/options/help.rs
Add missing --dereference, --almost-all, --help, --version to man pages. 
Add --dereference, --almost-all to CLI --help message.
Fixes #488
> docs: Add missing options to man page and CLI --help info

- README.md
Corrects a small typo in the description of the `--colo[u]r` option's parameters.
> docs: correct color option spellings

- Cargo.toml
I was trying to debug #521 and was very confused when my breakpoints weren't working at all.
I mean, not having debug symbols defeats the purpose of a debug profile in the first place. So I think it's best to reenable it.
> fix: reenable debug symbols in debug builds

- src/output/grid.rs
- src/output/grid_details.rs
Reopening #548 in different issue.
> fix: Display offset for filenames with spaces

- Cargo.lock
- Cargo.toml
- src/output/table.rs
- src/output/time.rs
Parts of `once_cell` are already in `std`, and the `Lazy` part is going to be implemented later.
`clap` also depends on `once_cell`, so after the clap PR gets merged there's going to be one less dependency.
> refactor: replace `lazy_static` with `once_cell`

- src/output/icons.rs
Added Typst files to the recognized files, the unicode character 𝐭 is used to tag each "typ" files.
Test Done.
Tested on Linux and MacOS.
> feat: add Typst to the recognized files

- completions/zsh/_eza
Changed from "`" to "'" as it is in others completions
closes #571
> fix(completions): changed quote in --almost-all completion

- man/eza.1.md
- src/options/file_name.rs
- src/options/vars.rs
Adds support for a new `EZA_ICONS_AUTO` environment variable that, if set, automates the same behavior as using `--icons` or `--icons=auto`. Any explicit use of `--icons=WHEN` overrides this behavior.
This is just a feature I thought I'd try implementing for my own use because I like having icons always on and figured it could be useful for others. This is also my first ever open source Rust project contribution so please feel free to give feedback!
> feat: create EZA_ICONS_AUTO environment variable

- flake.nix
- treefmt.nix
The pre-commit-hooks now use the treefmt formatter list. The `toFilter` list is used to filer the formatters not supported by treefmt.
I also added the statix formatter. iirc I also did this in #462
> ci: refactor pre-commit-hooks

- snap/.gitignore
- snap/snapcraft.yaml
Snap requires a `base` so I set it to `core22` and add some missing optional metadata for `website`, `contact`, `issues`, `source-code`, and `license`.
Also removed the `.gitignore` file since else `snapcraft` complains about that.
> fix: Snap requires a base

- man/eza.1.md
- src/options/help.rs
`--smart-group` is only applicable if `--group` is given.
Move its description to be after `--group` in the "LONG VIEW OPTIONS" section.
> fix(docs): move `--smart-group` to long view options

- Cargo.toml
This adds:
```toml
[profile.release]
panic = 'abort'
```
Saving `0.1` megs by making the binary 1.7M -> 1.6M
> feat: abort on panic (saving 0.1 M)

- completions/zsh/_eza
> fix(docs): Escape ` in zsh completions

- src/output/grid.rs
Resolves #578. This just adds the `classification_width` in one case that was left out for the approximate calculation of width in grid view. as mentioned [here](https://github.com/eza-community/eza/pull/583#issuecomment-1788921591)
> fix: calculate width correctly when using grid icons & classify

- src/main.rs
> fix: add bare git_repos fn if feature git is disabled

- completions/bash/eza
- completions/fish/eza.fish
- add --color-scale-mode to the bash completions
- add --colour-scale-mode to the bash and fish completions
Closes #707
> fix(completions): add color-scale-mode to bash and fish

- src/output/escape.rs
There's an issue with the way symlinks are quoted when their destination has spaces in the name.
Below is a set of test cases that demonstrates the problem:
```
λ eza -l bug-test
.rw-r--r-- 0 zacc  9 Dec 17:53 'file with spaces'
lrwxrwxrwx - zacc  9 Dec 17:54 'symlink-to-dest-with-spaces -> /tmp/file with spaces' # <-- this one
lrwxrwxrwx - zacc  9 Dec 17:53 symlink-without-spaces -> /tmp/test
lrwxrwxrwx - zacc  9 Dec 18:24 ''symlink with spaces to dest with spaces' -> /tmp/file with spaces' # <-- and this one
lrwxrwxrwx - zacc  9 Dec 17:53 'symlink with spaces' -> /tmp/test
```
In `symlink-to-dest-with-spaces`, the link has no spaces, but the destination does. `eza` quoted the entire link display, instead of just the destination.
In `symlink with spaces to dest with spaces`, the link and …
> fix(output): quote symbolic links correctly when their destinations contain spaces

- src/output/file_name.rs
- src/output/grid.rs
- src/output/grid_details.rs
When UTF-8 characters were present in the filename (cyrilic characters or french accents for example) the bare_width function returned the size of the ascii string.
Using UnicodeWidthStr::width to get the width fixes the issue.
Fixes #566
> Fix offset widths in grid mode with utf8 filenames

- src/output/color_scale.rs
When adding two -a options, you request that dotfiles *and* . and .. are displayed. But the -R triggers the recursion function, which caused the color scalar to recurse into ., causing a stack overflow.
This fixes #753
> fix: stack overflow when '-laaR' are used

- src/main.rs
This patch fixes the crash when the --git-repos flag is used on an directory that doesn't have read permissions.
Fixes: #767
> fix: crash using --git-repos on unreadable dir

- src/main.rs
This tries to improve #778 by removing an avoidable `.unwrap()`.
I also considered getting the `.path()` in a separate `.map()` on the iterator, not sure what's best:
```rs
.filter_map(|entry| entry.ok())
.map(|entry| entry.path())
```
> Avoid `unwrap()` by changing filter-then-map to `filter_map`

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- rustfmt.toml
- src/theme/mod.rs
- refactor: change cast to coertion, remove rustfmt skip and clippy lint ignore directives
- chore: remove rustfmt config file that has a nightly only option in favor of rustfmt skip directive which is already in place
- chore: fix small typo in pull request template
> Small changes for DX

- INSTALL.md
add a manual install option for those Linux not listed in the doc, with a small fix for those who previously installed original exa and might already have related alias.
> docs: add manual installation section

- Cargo.lock
- Cargo.toml
- src/output/details.rs
For 9 years now, `scoped_threadpool` was used while rendering the the details view. However, using `scoped_threadpool` comes with a couple of downsides:
- `MaybeUninit` was used to create memory for the threads to write in.
- Hence, `unsafe` had to be used to write to it.
- But also, a `Mutex` had to be used to provide access to the `Vec`, but that theoretically should not be necessary, since each thread writes into its own part of the `Vec`.
The `scoped_threadpool` solution was alright 9 years ago, but now we have `rayon` and we can do all of this in safe Rust, without `Mutex` and `MaybeUninit`!
Bonus: it's significantly faster! Here's a hyperfine experiment on my home folder:
```
❯ hyperfine -L eza eza-rayon,eza-scoped-threadpool "./{eza} ~ -Rl"
Benchmark 1: ./eza-rayon ~ -Rl
Time (mean …
```
> Replace `scoped_threadpool` with `rayon`

- src/fs/dir.rs
- src/output/file_name.rs
- src/output/table.rs
Just a small refactor, should have no effect except for saving a few lines of code.
> refactor: use `#[default]` attribute instead of custom impl for enums

- src/output/file_name.rs
More speedups! In my [previous PR](https://github.com/eza-community/eza/pull/833) I mentioned being baffled by the `readlink` and `getcwd` and I figured out where they came from: `File::mount_point_info`, which calls `std::fs::canonicalize`. The easy fix was to not call that when it's not necessary, which turns out to be most of the time!
Here's a benchmark:
```
❯ hyperfine -L eza eza-old,eza-new "./{eza} -R"
Benchmark 1: ./eza-old -R
Time (mean ± σ):     744.0 ms ±   9.3 ms    [User: 275.2 ms, System: 465.3 ms]
Range (min … max):   734.2 ms … 766.0 ms    10 runs
Benchmark 2: ./eza-new -R
Time (mean ± σ):     313.3 ms ±   3.0 ms    [User: 142.2 ms, System: 169.4 ms]
Range (min … max):   309.7 ms … 318.8 ms    10 runs
Summary
./eza-new -R ran
2.37 ± 0.04 times faster than ./eza-old -R
```
> Do not pre-compute MountInfo to reduce readlink calls

- completions/fish/eza.fish
- completions/nush/eza.nu
- completions/zsh/_eza
I realized there are duplicated entries in shell completions. They had different description, so I merged their description and removed the extra one.
I also realized that the bash completion is lacking a lot, but that is out of the scope of this PR.
I used the following to double check for duplicates. Perhaps these can be used to create automated tests for the repo. Note that they are all in Bash/Zsh syntax and not Fish and Nushell:
For Zsh:
```sh
cat zsh/_eza \
| grep -P '^\s*[{-]' \
| sed -E 's/".+$//g' \
| sed -E 's/(^ *)|(} *$)|(\{)//g' \
| sort \
| uniq -c \
| sort
```
For Bash:
```sh
cat bash/eza \
| grep '^\s*-' \
| sed -E 's/(^\s*)|\)//g' \
| tr '|' '\n' \
| sort \
| uniq -c \
| sort
```
For Nushell:
```sh
cat nush/eza.nu \
| sed -E 's/(^\s*)|( *# .+)|\)|^[^-]+$//g' \
| tr '(' …
```
> fix: duplicates in shell completions

- INSTALL.md
As was recommended in #810, could be helpful to others in that situation/environment.
> docs: add target arch to deb PPA installation for strict apt environments

- src/output/grid.rs
Fixes https://github.com/eza-community/eza/issues/845
I'm hoping that the next version of `uutils-term-grid` will make these manual calculations unnecessary. That should keep future bugs like this to a minimum.
> fix: classification width should be taken into account with -F=auto

- src/output/icons.rs
This PR adds icons for both `.gql` and `.graphql` extensions.
I followed the alphabetical order of the icons. And just added two more icons to the list, you can check them in the screenshot below:
This closes #552 
I tested locally against a directory of graphql files. I ran the local tests with cargo and everything was ok.
> feat: adding icons for graphql extensions

- src/output/render/flags_bsd.rs
The NetBSD pkgsrc version just disabled the feature.
Fix implemented on the recommentation of the comment on http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/eza/patches/patch-src_output_render_mod.rs
Renamed the rust flags_to_string into wrapper_flags_to_string to avoid overlap with the extern C import which had the same name.
Now NetBSD file flags are supported and the build does not fail anymore.
fixes #861
> Fix: NetBSD did not have fflagstostr and as such did not build properly

- src/output/icons.rs
By using the same icon for `fsproj` files as `fs` (and other fsharp files) we use the same behaviour as for csharp files (`csproj` files also use the same icon as `cs` files).
> feat: Use fsharp icon for fsproj files (similar to cs/csproj)

- .github/workflows/unit-tests-bsd.yml
- src/fs/feature/xattr.rs
Add support for building in FreeBSD / NetBSD / OpenBSD via [vmactions](https://github.com/vmactions) in the CI.
While here also address the following warnings in the CI
```
error: unneeded sub `cfg` when there is only one condition
--> src/fs/feature/xattr.rs:115:11
|
115 |     #[cfg(any(target_os = "linux"))]
|           ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `target_os = "linux"`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#non_minimal_cfg
= note: `-D clippy::non-minimal-cfg` implied by `-D warnings`
error: this expression creates a reference which is immediately dereferenced by the compiler
--> src/fs/feature/xattr.rs:476:43
|
476 |                 let value = get_attribute(&path, &attr_name, follow_symlinks, getter)?;
| …
```
> build: add FreeBSD / NetBSD / OpenBSD to CI.

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/options/view.rs
- src/output/details.rs
- src/output/grid.rs
- src/output/grid_details.rs
- tests/gen/long_time_style_custom_non_recent_empty_nix.stderr
- tests/gen/long_time_style_custom_non_recent_none_nix.stderr
- tests/gen/long_time_style_custom_recent_empty_nix.stderr
This will require a small addition to uutils-term-grid: https://github.com/uutils/uutils-term-grid/pull/37, hence it's still a draft. It also needs a bit more cleanup. I think that with the `ansi-width` crate, which I both added as a direct dependency and as a transitive dependency, most of the `TextCell` code could be removed, but I'll take it bit by bit and start with the grid layouts only.
Here's a summary:
- All of the width calculations are gone, because `ansi-width` can just compute the right width.
- The grid-details layout had to be rewritten because I remove `fit_to_columns` from `uutils-term-grid`, because I didn't think that it fit the purpose of the library. Luckily, the new implementation is much shorter and, I think, much clearer. It just renders a table and throws the rows …
> Port grid and grid-details to new uutils-term-grid

- src/info/filetype.rs
- src/output/icons.rs
Support `.hh` as an additional C/C++ extension. (Note that `.cc` is already supported.)
> feat: add filetype and icon for .hh extension

- src/fs/file.rs
In 4799a4924998e31bf1f501a2c6c0f006d1e427d3 a check for broken symlinks was introduced, but failed to check if a given argument actually **is** a symlink. This change simply adds that check.
Closes #887 but could also be the cause for other bugs, where absolute paths are needed.
Ran `cargo test`  for existing tests and verified the correct output for `eza --hyperlink *PATTERN*` manually, see:
> fix: bugfix to resolve absolute paths that are not symlinks

- src/output/icons.rs
Cron optionally allows you to use a '/etc/cron.minutely' directory to trigger automated events on a per-minute basis.
There is currently no special icon set for cron.minutely, while the other cron.* directories do, so I added cron.minutely to the DIRECTORY_ICONS mapping and applied the `Icons::FOLDER_CONFIG` icon like the other cron.* directories.
I have tested it with `cargo check` and `cargo build`.
I apologize if I made any mistakes. I'm not too familiar with GitHub.
> feat: add icon for "cron.minutely" directory

- README.md
``
1. Added link to the man pages in repo readme
2. Inserted a couple keywords typically associated with instructions
3. Also while I was there: 
- Fixed the heading hierarchy 
- Removed the entire "Command-line options" section from being in a `<details>` collapsible section. Instead made the content of the 3 subheadings collapsed which I infer from the wording was the original intention.
``
1. man pages are easy to miss and not widely available elsewhere
2. keywords ("quick", "overview", "documentation") that I thought would help someone find the instructional section using `ctrl`-`f`. Since content is still mostly collapsed it isn't visible when you quickly scroll the page.
3. The whole section being collapsed makes it difficult to notice the useage information. It breaks the …
> docs(readme) command line options section: add link to man pages + fix  structure

- man/eza.1.md
I believe this feature changed name sometimes during development, but it's still called decay in the description of EZA_MIN_LUMINANCE, which confused me while I read the man page.
> docs(man): replace decay with color-scale

- src/output/mod.rs
Apparently this line is required for the Windows build, but leads to warnings on systems that build the eza port with a port of rust 1.77.2, which at this time seems to be limited to the BSDs.
Rather than selectively suppress the warning, I suggest to only include this line where needed.
> fix: change windows-only imports to be windows-only

- README.md
This puts the packages into 3 columns instead of just one.
It allows an easier overview and reduces the amount of scrolling.
> docs(README): use 3 columns for packaging status badge

- src/output/icons.rs
This PR adds support (icon) for the [Nushell](https://github.com/nushell/nushell) extension, i.e. `nu`
> feat(icons): add icon for Nushell extension

- .github/workflows/audit.yml
- deny.toml
At the moment the audit workflow only checks the `advisories` but not
`bans`, `licenses`, or `sources`. This removes said limitation.
> feat(github): extend deny check in audit workflow to all

- .github/ISSUE_TEMPLATE/bug_report.md
Some issues might be shell or terminal specific, so we should explicitly
ask for those information as well in the bug report template.
> feat(github): ask for shell and terminal in bug report template

- README.md
- completions/fish/eza.fish
- completions/nush/eza.nu
- completions/zsh/_eza
- man/eza.1.md
- src/fs/filter.rs
- src/options/filter.rs
- src/options/flags.rs
Currently you can use `--only-dirs` and get only directory output, or you can use `--only-files` and get only files. 
Someone requested the ability to hide symlinks (for some MacOS feature where they use symlinks to make their directory structure more unix-like), but I think it makes more sense to also be able to filter and get all directories or all files (symlinks or otherwise), as well as hide symlinks in normal output.
> feat: add --no-|show-symlinks flags for filtering output

- completions/zsh/_eza
Before this change the shell would report a parsing error, which was due to missing line breaks after the newly introduced symlinks flags. This commit fixes that issue.
Closes https://github.com/eza-community/eza/issues/1038
> Fix missing line breaks in zsh completions

- .pre-commit-config-non-nix.yaml
- CONTRIBUTING.md
For those of us who don't use nix on a daily basis, it's nice to have the option of getting `rustfmt` + `clippy` running before we commit.
> feat: add non-nix pre-commit rustfmt and clippy hooks

- Cargo.lock
Rust 1.80 fails to build `time` crate versions `< 0.3.35`: https://github.com/time-rs/time/issues/693, this bump fixes that.
Built the package before the change and after to verify the issue is gone.
> build(deps): bump time dependency

- src/output/grid_details.rs
Grid details view had been prevented only by console width being unavailable.
This changeset implements `EZA_GRID_ROWS` as secondary grid details inhibitor, preventing grid details view if the minimum rows threshold is not reached by the grid which would be rendered.
Fixes complaint at https://github.com/eza-community/eza/issues/66#issuecomment-2198567463
Side note: `EZA_GRID_ROWS` only applies to `--long --grid`, but not to _non-details_ `--grid` view. Looking at the code and [documentation](https://github.com/eza-community/eza/issues/1044#issuecomment-2200573562), this appears to be intentional.
> fix: implement `EZA_GRID_ROWS` grid details view minimum rows threshold

- .github/workflows/unit-tests-bsd.yml
- src/fs/feature/git.rs
- src/fs/fields.rs
- src/fs/file.rs
- src/output/details.rs
- src/output/grid_details.rs
Address `clippy` warnings from FreeBSD builds, compiling under.
```
rustc 1.79.0 (129f3b996 2024-06-10) (built from a source tarball) 
```
> fix: FreeBSD build.

- INSTALL.md
Eza is currently available and working in Flox.
Sadly, no repology badge for Flox just yet.
> Add Flox to installation instructions

- man/eza_colors.5.md
- src/output/file_name.rs
- src/theme/default_theme.rs
- src/theme/mod.rs
- src/theme/ui_styles.rs
In the discussion https://github.com/orgs/eza-community/discussions/891 the user asks about the ability to make the icon color different from the file name color. I took a peek into the code and actually ended up implementing this functionality.
So this adds the `EZA_COLORS` variable `ic` for icon which ends up as an `Option<Style>` in the `UiStyle` with `None` as default. The logic in the `FileName.paint` is adjusted to apply the icon style when the value is `Some` and otherwise fall back to the usual behavior, namely that the icon color matches the file name color.
> Color Setting for Icons

- README.md
- docs/theme.yml
- man/eza_colors-explanation.5.md
Include theme file in list of additional features since `exa`, add complete documentation to the eza colors explanation manpage, removed the 'themes' directory, as we will not be including any more than the initial example in this repo as discussed on matrix, and moved the example theme to 'docs'
> docs: add further documentation about theme file

- src/fs/filter.rs
- src/main.rs
- src/output/details.rs
> fix: selectively filter files when recursing

- src/options/config.rs
I'm currently working on an [eza-themes](https://github.com/eza-community/eza-themes) repo to test out theming, find issues and improve ergonomics. One thing in particular I noticed is the poor deserialization of the `Color` type. While hardcoded colors can simply be specified by name, e.g. `White`, working with specific RGB values isn't very pretty and requires to use custom YAML tags your editor is gonna complain about:
This PR adds a custom deserialization function that recognizes hardcoded colors, color codes and hex colors, all in upper- and lowercase writing, which makes theming significantly more intuitive:
It also adds a few unittests to said function and fixes a typo elsewhere in the config module.
I would hold creating any themes in the currently still private …
> Simplify Colorization through Theme File

- src/output/file_name.rs
fix https://github.com/eza-community/eza/issues/843
https://docs.rs/percent-encoding/latest/percent_encoding/fn.utf8_percent_encode.html
> fix: convert empty space to `%20` when render hyperlinks

- src/output/file_name.rs
fix #1131
Wasn't sure if we should revert or not
> fix: remove non_alpha from percent encoding to fix hyprlinks

- src/output/icons.rs
https://en.wikipedia.org/wiki/OPML
> OPML (Outline Processor Markup Language) is an XML format for outlines.
`file` identifies a sample `.opml` file as "XML 1.0 document, Unicode text, UTF-8 text".
> feat: add `opml` file extension

- flake.nix
Otherwise, `cargo build` fails because the `ld` linker cannot locate the library.
```
= note: ld: framework not found Security
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
> fix: Inject Security apple sdk framework for `nix develop`

- INSTALL.md
- Hi, [x-cmd](https://www.x-cmd.com/) is a **toolbox for Posix Shell**, offering a lightweight package manager built using shell and awk.. It helps you download eza release packages from the internet and extract them into a unified directory for management, without requiring root permissions.
- **I mean, can the installation method provided by x-cmd be added to the eza installation.md?**[The installation method for the x command](https://www.x-cmd.com/start/).
```sh
x env use eza
x eza
```
- We wrote a [eza introduction article](https://www.x-cmd.com/pkg/eza) and a [demo](https://www.x-cmd.com/1min/eza)
> docs(install): add x-cmd method to install eza

- .github/workflows/flake.yml
In #1146, I was made aware that we don't run the nix3 related CI command
with full logs displayed.
This adds the `-L` flag to those command invocations to address that.
This will be tested in the CI for the PR.
> ci: full nix3 command output in logs

- completions/fish/eza.fish
- completions/nush/eza.nu
- completions/zsh/_eza
- man/eza.1.md
- src/main.rs
- src/options/flags.rs
- src/options/help.rs
- src/options/view.rs
- src/output/details.rs
- src/output/mod.rs
- tests/cmd/follow-symlinks_unix.stdout
- tests/cmd/follow-symlinks_unix.toml
- tests/cmd/tree_unix.stdout
- tests/cmd/tree_unix.toml
- tests/gen/long_time_style_custom_non_recent_empty_nix.stderr
- tests/gen/long_time_style_custom_non_recent_none_nix.stderr
- tests/gen/long_time_style_custom_recent_empty_nix.stderr
Before:
```
/tmp/test-recursive-dir-symlinks
├── dir
│  └── test.txt
└── symlinkdir -> /tmp/test-recursive-dir-symlinks/dir
```
After:
```
/tmp/test-recursive-dir-symlinks
├── dir
│  └── test.txt
└── symlinkdir -> /tmp/test-recursive-dir-symlinks/dir
└── test.txt
```
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
This will make `eza` resolve symlinks pointing at valid directories like a
regular directories, meaning: if requested, unravel them recursively. This is
handy in cases where an inspected directory contains multiple layers of symlink
indirection (hi nix!)
I've confirmed that loops (situations where symlinks from two directories
cross-point to each other) are handled gracefully by `eza` already (reporting
an error but proceeding to handle the rest of the files.) See …
> feat: recursively walk symlinks pointing at dirs

- flake.nix
- man/eza.1.md
- man/eza_colors-explanation.5.md
- man/eza_colors.5.md
The first commit fixes cross-references in the man page.
The second commit corrects the file type color descriptions to match current source. 
https://github.com/eza-community/eza/blob/e7882ceb427cc13ab337d688fd650674f3478800/src/theme/default_theme.rs#L110-L123
P.S.: The version packaged in nixpkgs has `$version` instead of the version number; I've opened https://github.com/NixOS/nixpkgs/pull/345185.
> Fix cross-references and colors in man pages

- man/eza.1.md
Resolves: #1058 
Tested by:
```
just man
man ./target/man/eza.1
```
and the new line was added and formatted consistently with the others.
> docs(man): document that exit 13 == permission denied

- README.md
- completions/fish/eza.fish
- completions/nush/eza.nu
- completions/zsh/_eza
- man/eza.1.md
- powertest.yaml
- src/fs/filter.rs
- src/options/filter.rs
- src/options/flags.rs
- src/options/help.rs
For example, it will be quite useful to use this feature alongside --tree as then when printing a deeply nested directory structure, all the files within each directory will be listed first and then the remaining deeply nested directory subtree within it will be printed, giving the users a far better understanding of which files are within each folder.
This addresses issue #872
> feat: show directories last

- src/theme/mod.rs
Description
Old ms windows command prompt cant directly handle all of the ansi terminal control codes.
How Has This Been Tested?
The fix is to use the following snippet, as per the upstream examples in the nu_ansi_term
```
#[cfg(windows)]
nu_ansi_term::enable_ansi_support().unwrap();
```
> fix: colors in old ms command prompt

- src/options/help.rs
The help text and the available flags had become out of sync, which also distorts the completion in bash. Regrouped the options also a bit to be more logical when reading the help text.
Fixes #400 - bug: Test and fix all bash completions
> fix: bring help text in line with available flags

- INSTALL.md
This or just adds the option for people to install `eza` on linux and windows using `fox`
> chore: add fox installation option

- src/output/file_name.rs
- tests/cmd/absolute_file_all.stdout
- tests/cmd/absolute_file_all.toml
The parent path of a file was added even with absolute={on,follow}, causing the parent path being prepended to the resolved (absolute) filepath.
Fixes: #1151
> fix: do not print parent filename with --absolute=on

- src/fs/dir.rs
- src/fs/file.rs
- src/fs/filter.rs
- src/main.rs
- src/output/color_scale.rs
- src/output/details.rs
- src/output/table.rs
This is a draft because I made this PR more to spark some conversation than to actually change the code. It could still be merged if I clean it up but (spoiler alert) the improvement is very small for now. So here goes.
> **Note**: I also have to double check the `deref_links` logic. I'm pretty sure I got that wrong, but it wasn't my focus for now. And the error handling is sloppy too.
`eza` is super fancy, but sometimes quite slow. As seen in some issues and discussions:
- https://github.com/eza-community/eza/issues/830
- https://github.com/orgs/eza-community/discussions/816 (this PR is based on some ideas I posted there)
(and probably some more, I've only started tracking this recently)
**This is not necessarily a problem**: as I understand it, `eza` is meant for fancy output first and …
> Reuse FileType from DirEntry

- Cargo.lock
- src/fs/file.rs
Co-authored-by: Erwin van Eijk <235739+erwinvaneijk@users.noreply.github.com>
This is a second (third?) attempt at getting this merged, I've copied the
changes from #1175 by @erwinvaneijk, I think it's gonna work this time.
Nothing yet, will run `nix flake check` and do basic sanity checks before merge.
> fix: remove depricated `chrono` `from_timestamp_opt`

- src/options/help.rs
- tests/ptests/ptest_2439b7d68089135b.stdout
Fix #1211  a typo `--get-repos-no-staus` in `help.rs`
> Fix typo `--get-repos-no-status` to `--git-repos-no-status`

- CHANGELOG.md
I started this branch because I noticed some warnings while building eza with `cargo build --release`.
```
warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp_opt`: use `DateTime::from_timestamp` instead
--> src/fs/file.rs:734:24
|
734 |         NaiveDateTime::from_timestamp_opt(
|                        ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp_opt`: use `DateTime::from_timestamp` instead
--> src/fs/file.rs:763:24
|
763 | ...   [NaiveDateTime::from_timestamp_opt(self.me](http://naivedatetime::from_timestamp_opt(self.me/)...
|                      ^^^^^^^^^^^^^^^^^^
warning: `eza` (lib) generated 2 warnings
warning: `eza` (bin "eza") generated 2 …
```
> chore: changelog spelling

- Cargo.toml
It looks like this list hasn't been updated for new, removed, moved, or renamed files in a while.
I've added all folders / files that are not useful for consumers of the published crate to the "package.exclude" list.
This results in a reduction of the .crate file size by ~80%, from 1.24 MB to 205 kB.
> chore: update package.exclude list in Cargo.toml

- Cargo.lock
- Cargo.toml
I can't push changes to the #1207 branch so I'm duplicating this here.
palette_derive 0.7.6 introduces a new dependency on the by_address crate,
which looks like it has correctness / soundness issues (uncovered by
running tests in "release" mode or in miri):
https://github.com/mbrubeck/by_address/issues/9
Signed-off-by: Fabio Valentini <decathorpe@gmail.com>
> fix(deps): palette v0.7.6 -> v0.7.5

- Cargo.lock
Fixes cross-compiling to osx-arm64 with gcc 18.
Done via: `cargo update libz-sys`
See also:
* fails: https://github.com/conda-forge/eza-feedstock/pull/32
* builds (=commit of this PR applied): https://github.com/conda-forge/eza-feedstock/pull/35
> Fix cross-compiling: Update libz-sys to 1.1.20

- Cargo.lock
- Cargo.toml
- src/output/mod.rs
- **build(deps): bump terminal_size from 0.3.0 to 0.4.1**
- **fix: use safe terminal_size_of**
- **fix(windows): use terminal_size_of with borrowed raw handle**
> refactor(deps): terminal_size

- src/output/icons.rs
New glyph from Nerd Font (still present in 3.3.0 release)
- Add Gleam icon for Gleam source files the icon is a basic Smiley Star Glyph, not the official Gleam icon (as it doesn't exist in Nerd Fonts for now)
> feat: add Gleam lang icon

- .github/workflows/unit-tests.yml
- Bump FreeBSD to `14.2`
- Bump NetBSD to `10.1`
Release notes can be found here: 
- https://www.freebsd.org/releases/
- https://www.netbsd.org/releases/formal-10/NetBSD-10.1.html
> ci: bump FreeBSD / NetBSD versions.

- .github/workflows/unit-tests.yml
The FreeBSD CI seems to be failing in several PRs due to it using the latest available rust version on FreeBSD (1.83), see discussion: https://github.com/eza-community/eza/pull/1336
This attempts to set a specific version by using rustup instead of `pkg install`. We could also use the version matrix then, I think.
Also, this is the LEET/1337 PR :) ... had to be BSD related of course XD
> Use Specific Rust Version in FreeBSD CI

- .github/workflows/unit-tests.yml
- rust-toolchain.toml
Even though the projects MSRV is now 1.78 the unit tests are still using 1.70.
This changes the current matrices to use "msrv" rather than the actual version to extract that to a single environment variable. Meanwhile this also adds that rust version matrix strategy to the freebsd and netbsd unit tests.
Note that openbsd is not yet supported by rustup and there still just uses the default installation method.
> ci(unit-tests): fix and unify msrv and add matrix to free/netbsd

- justfile
This adds `libgit` enabled arm builds, meaning we'll ship both with and
without libgit for arm releases. The ever growing justfile is reminding
me of the horrors often seen in Makefiles... but fixing that is left as
an exercise to the reader (likely me when I find the spoons).
This will probably be adjusted slightly on release day, experience shows
that the gh-release recipe resists improvements, but I'll deal with that
on <commit date> + ~thursday.
Closes: #1138 #1060
It hasn't, but it will be on ~thursday. It's easy to revert if it becomes release blocking.
> build(release): add libgit alternative for arm builds

- INSTALL.md
This PR adds instructions to install `eza` with [Pixi](https://pixi.sh/). This installation method will work for Linux, macOS, and Windows and adds `eza` to the user's PATH.
> Add Pixi installation instructions

- .github/workflows/unit-tests.yml
Magic Nix Cache has been deprecated due to a change in the underlying
GitHub APIs and will stop working on 1 February 2025.
> ci: remove magic nix cache

- man/eza_colors-explanation.5.md
- src/theme/default_theme.rs
As reported in #1406, currently default theme uses white for temporary files, which causes them to appear invisible on white background. Additionally the man page describes temp files color as grey.
I've changed the color to dimmed default foreground color, which ensures it will stay visible on both black and white backgrounds.
This _in most cases_ means grey (dimmed white or dimmed black), but it's not entirely true as default foreground color can be set to anything. I've changed the man page to reflect that, but I can drop it if you think "grey" is close enough.
Alternatively I can just set the temp files color to grey, but I think dimmed is a better option as it will work well on any background, as long as terminal has a foreground color with a proper contrast; _and_ I think a dimmed …
> fix(theme): make temp files visible on white background

- src/fs/feature/git.rs
- src/output/render/git.rs
- src/output/table.rs
Fix #1434
Just pushing something I was working on a bit more than a year ago and that I think is still relevant.
If this change is not accepted, we would still have to change the code because indexing `String` doesn’t work well with UTF-8. I got alignment issues because of branch name with `é` in it, it’s two code points but one character, and it could also result in splitting a code point and trying to display an incorrect character).
> fix(git-repo): Don’t truncate branch name

- INSTALL.md
This PR updates the Fedora install instructions in `INSTALL.md` to reflect that `eza` is no longer available in Fedora 42+ due to the absence of a package maintainer.
- Added a warning and Fedora 42-specific note
- Suggested downloading binaries or building from source
- Invited community members to maintain the Fedora package
Closes #1456
> docs: update Fedora install instructions for Fedora 42

- src/theme/mod.rs
This shouldn't affect behavior in any way, since glob patterns of the form `*.foo` / `*.bar` are disjoint, so it doesn't *matter* which order we search them in.
The exact order of disjoint patterns like that aren't preserved anymore, so the test suite needed to change a bit.
`hyperfine "./target/release/eza --color=always /nix/store"` on 3ad8132f874f66945eca3511491afa85c5f43ebe gets
> Benchmark 1: ./target/release/eza --color=always /nix/store
>  Time (mean ± σ):      5.109 s ±  0.488 s    [User: 4.682 s, System: 0.383 s]
>  Range (min … max):    4.691 s …  6.262 s    10 runs
when on this branch (d2ff56bba42012f07ebad2e1188ba7abb51e7d2b), it is
> Benchmark 1: ./target/release/eza --color=always /nix/store
>  Time (mean ± σ):     724.7 ms ±   6.3 ms    [User: 379.4 ms, System: 339.9 ms]
> …
> perf: use a hashmap when possible for file extension matching

- Cargo.lock
- Cargo.toml
- src/fs/file.rs
- src/output/table.rs
- src/output/time.rs
Rust 1.80 has a proper implementation of LazyLock, which, when used, removes the dependency on once_cell.
- update toolchain to 1.80.0 from 1.70.0
- remove once_cell from dependencies
Fixes: #1169
> feat(once_cell): remove dependency on once_cell

- src/output/icons.rs
Added an icon association for `.stowrc` files to `output/icons.rs`. `.stowrc` is an ignore-type file for [GNU Stow](https://gnu.org/software/stow). The icon is the `nf-fa-cow (eef1)`, It is available in all _Nerd Font_ variants. It is a cow icon due to common usage of '_symlink farms_' and other farm-related terms in the manual and info pages for GNU Stow.
> chore(output): add icon for '.stowrc' files

- .pre-commit-config-non-nix.yaml
Otherwise I get a bunch of errors similar to this one:
```
error: failed to run `rustc` to learn about target-specific information
Caused by:
process didn't exit successfully: `/home/ariasuni/.rustup/toolchains/1.81-x86_64-unknown-linux-gnu/bin/clippy-driver /home/ariasuni/.rustup/toolchains/1.81-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
--- stderr
error: multiple input filenames provided (first two filenames are `-` and `src/options/vars.rs`)
error: failed to run `rustc` to learn about target-specific information
```
> fix(pre-commit): make clippy work again

- src/output/icons.rs
This PR adds icon support for .ipynb (Jupyter Notebook) files. I've assigned the notebook icon  \u{e678} the same one used in vscode for notebook files.
Let me know if a different icon would be prefered!
> feat(icons): add support for .ipynb file icons

- src/fs/dir.rs
- src/fs/file.rs
- src/main.rs
- src/output/color_scale.rs
- src/output/details.rs
Previously, recursive directory traversal caused excessive open file descriptors, leading to OS errors like:
```sh
eza --almost-all --recurse >/dev/null
```
Which was caused by directories being read too early, keeping file handles open for too long. Now, `to_dir` only sets up the `Dir` instance without reading contents and waits to read directories until needed, reducing open files
fixes: https://github.com/eza-community/eza/issues/1387
> fix: too many open files error in recursive directory traversal

- man/eza.1.md
Fixed #981 
The `--absolute` option was available in CLI but missing from the man page documentation.
Added documentation for `--absolute=WHEN` with all valid settings (`on`, `follow`, `off`) in the DISPLAY OPTIONS section.
> docs(man): add missing --absolute option to man page

- src/main.rs
- src/options/view.rs
- tests/gen/long_time_style_custom_non_recent_empty_nix.stderr
- tests/gen/long_time_style_custom_non_recent_none_nix.stderr
- tests/gen/long_time_style_custom_recent_empty_nix.stderr
When output is not a TTY (e.g. when piped), fix grid view instead of
outputting oneline view.
BREAKING CHANGE: When using --grid, the output for non-TTY is now the
grid view as well, breaking scripts that may have erroniously used
--grid.
Fixes #1545
- `nix flake check -L`.
- Sanity checks on command output for the bug.
Closes #1545.
> fix(view)!: make --grid work when not in TTY

- Cargo.toml
A simple fix that makes `cargo deb` work.
Before this PR:
```
❯ cargo deb
error: unable to read license file: LICENCE
cause: No such file or directory (os error 2)
```
After:
```
❯ cargo deb
Finished `release` profile [optimized] target(s) in 0.08s
.../eza/target/debian/eza_0.23.0-1_amd64.deb
```
**NOTE**: One also has to run `just man`, and have `pandoc` installed, before the deb will build.
> fix: `cargo deb` metadata to `LICENSE.txt`

- snap/snapcraft.yaml
New contributor, so bear with me. I happily accept PR critique.  🙇🏻‍♀️
I want to see eza on snap, so I'm trying to make that happen! I couldn't get it to build as-is, so here are the modifications I've made.
It doesn't look like libgit2 is available, and even though git2-rs says it's included in the the libgit2-sys crate, that crate was also installed back when this file was written... I'm a little concerned about having to remove this line and would like to make sure no functionality is broken. `--git` and `--git-repos` are still working without it.
There are still a couple oddities during the build...
```
Pulling eza :: Downloading package: libnghttp2-14 - (2.0s)/snap/snapcraft/15775/lib/python3.12/site-packages/apt/package.py:810: Warning: W:Download is performed unsandboxed as root as …
```
> chore(snap): update snapcraft manifest for core24
